### ISSUE TITLE
Pass --legacy-peer-deps flag to link command ?

### ISSUE THREAD

**Issue by peraronsson** [bitmeal/nodegit-alpine#1] opened 2023-03-17 20:43 UTC
Hello,

I'm using `bitmeal/nodegit:0.27-16-alpine as builder` in a Dockerfile. However, I need to use the `--legacy-peer-deps` flag when I `install` and when I `link`. There doesn't seem to be any way to add that argument to the automatic linking, so I opted out of that, and instead tried to link manually. I have tried many different variations. However, I always end up with an error like this:

```
#0 50.97 npm ERR! code 1
#0 50.97 npm ERR! path /repo/node_modules/nodegit
#0 50.97 npm ERR! command failed
```

How should it be done?

**Comment by bitmeal** [comment] 2023-03-20 11:02
Could you please give an example of 
* what your environment looks like
* what command you are running
* your goal

If possible, provide a MWE of a `Dockerfile` and `package.json`/`package-lock.json`.

In general: When calling `npm install` without package names, but flags, the flags will be passed through to npm from the *linker*. When calling `npm install <package> [<package>...]` eventually present flags are not passed to the automatic linking process of *nodegit*.

**Comment by peraronsson** [comment] 2023-03-20 12:46
I found a solution: by adding the `legacy-peer-deps` argument to npm config, it is automatically used in every npm command issued.

`echo "legacy-peer-deps=true" >> .npmrc`

**Comment by bitmeal** [comment] 2023-03-20 23:21
Glad you found a solution! If the flag is necessary for all calls to `npm install`/`npm link` yours is likely even the best option.

I cannot give any further advice without additional information, as I cannot reproduce what you are experiencing. Flags and options are always passed through to *npm*, **except** when linking the preinstalled *nodegit* version.

Additional FYI: Newer versions should be available within the next hours, as some bugs have been fixed.

I will close this issue as it has been solved for you. Please feel free to reopen or add a new one.

**Closed as completed by bitmeal** 2023-03-20 23:21 UTC
